Add work section and about me section on portfolio
kalbek/Portfolio pull request #2
Opened 2023-02-17 20:20 UTC by kalbek

As part of the next step of the professional personal portfolio building project, the work history section and about me sections are included in this version

2023-02-17 20:57 UTC, adel-gu reviewed
# Status; INVALID PR ❌ 

Hi @kalbek 👋🏼 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  ⬇️ ⬇️ ⬇️ 

You have submitted a project, that contains a **REAMDE** file **without the main headers**, please consider following this [Microverse Template](https://github.com/microverseinc/readme-template), Ensure to fill out all the necessary content descriptions about your repo, The only **OPTIONAL** section is the **FAQ** but still highly recommended though.

**Best of luck 🍀** 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-18 03:26 UTC, didierganthier reviewed
Hi @kalbek ,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.

<img src="https://media.giphy.com/media/d2lcHJTG5Tscg/giphy.gif" />

## Invalid Code Review Request 🚫

- You have submitted a project, that contains a README file without the main headers, please consider following this [Microverse Template](https://github.com/microverseinc/readme-template), Ensure to fill out all the necessary content descriptions about your repo, The only OPTIONAL section is the FAQ but still highly recommended though.

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

2023-02-18 03:40 UTC, kalbek commented
Dear Adel,

Kindly, can you be more specific on what I have to correct now on the
portfolio?
Thank You.

Kaleb Bekele

On Sat, Feb 18, 2023 at 6:26 AM Didier Peran Ganthier <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Hi @kalbek <https://github.com/kalbek> ,
>
> While you put in a lot of hard work in this project, unfortunately, I
> cannot proceed with the review of your code.
>
>
> <https://camo.githubusercontent.com/ae631cc285437c804b5b30b913ddb3bd07ba4c17a5d1d416361b695b7df53927/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f64326c63484a544735547363672f67697068792e676966>
> Invalid Code Review Request 🚫
>
>    - You have submitted a project, that contains a README file without
>    the main headers, please consider following this Microverse Template
>    <https://github.com/microverseinc/readme-template>, Ensure to fill out
>    all the necessary content descriptions about your repo, The only OPTIONAL
>    section is the FAQ but still highly recommended though.
>
> Your Code Review Request will be marked as invalid in your Dashboard, but
> don't worry you can always try again! 💪
>
> Cheers and Happy coding!👏👏👏
>
> If you have any questions or need clarification on anything, feel free to
> leave a comment in the pull request thread and don't forget to tag me so
> I'll receive the notification.
>
> *Please note*
>
>    - To avoid confusion and delays, please do not open a new pull request
>    for re-reviews. Use the same pull request submitted for the first review,
>    unless otherwise instructed.
>
> ------------------------------
>
> *Invalid Code Review Request does not count towards the code reviews
> limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kalbek/Portfolio/pull/2#pullrequestreview-1304470814>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKUYJSOLYXY4L3EJMOPGJALWYA6PZANCNFSM6AAAAAAU72U7EY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-18 07:13 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @kalbek , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you have done an exceptional job but still there are some changes that needs to be addressed to continue to the next level.

## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 07:13 UTC, ABDULALI3468 commented on index.html
> +            </div>
Please consider adding these images as a background image of the section using the CSS property instead of using `img tags`.

## REASON:-

(decorations are always backgrounded images, not img tags)

2023-02-18 07:13 UTC, ABDULALI3468 commented on index.html
> +        </div>
Please consider adding these images as a background image of the section using the CSS property instead of using `img tags`.

## REASON:-

(decorations are always backgrounded images, not img tags)

2023-02-18 07:13 UTC, ABDULALI3468 commented on index.html
> +              <h1>About Me</h1>
Please consider using an `hx tag` here for the purpose of making it semantically correct. You can just replace it with any tag from `(h2 to h6)`. We did not use the `h1 tag` more than once on the page and used it only where we want browsers to know something about the page.

2023-02-18 07:13 UTC, ABDULALI3468 commented on index.html
> +            <p>Get My Resume</p>
A- Please consider using an `a tag or button tag` instead of a `p tag` to make it semantically correct.


B- Please consider adding the functionality of `hover and press` on the button. So when the button is hovered or pressed its style changes as follows. To achieve this you can add the following functionality of code into your CSS file.

```
.class:hover{
    background-color: #36B37F;
    color: white;
}
```

```
.class:active{
    background-color: #008552;
    color: white;
}
```

![image](https://user-images.githubusercontent.com/94223367/219846052-7000d009-18bc-4d25-9399-86b5de4d6387.png)

2023-02-18 07:13 UTC, ABDULALI3468 commented on index.html
> +                </div>
Please consider using the `ul for the list container instead of divs and similarly li tag for each list item` to make it semantically correct. 


## Remember:-
Moreover this problem exists in all of your cards in this section so consider making these changes everywhere.

2023-02-18 07:13 UTC, ABDULALI3468 commented on index.html
> +            </p>
Please consider using the same stlyes as presented in the Figma Tempalte you have chosen. Currently the major problem is with:- 

```
line-height: 32px;
color: #42526E;
and some margin after adding it.  
```

As its a project requirement.

2023-02-18 08:58 UTC, Shisui6 requested changes
Hi @kalbek , 

# Requires Changes 🍀
It seems you didn't implement any of the changes suggested by the previous reviewer😭
Please make sure to go through each of the suggested changes one by one and address each so that your project can be approved👍.


 ## Highlights
 - Descriptive PR title and summary ✅
 - Follows Github flow ✅
 - Good commit messages ✅

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +          <p>My Recent Works</p>
As the previous reviewer suggested, please us a `<hx>` tag here(`h2 to h6`). This is for semantic reasons as this text is considered a subtitle for your webpage

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +                <p>Multi-Post Stories Gain+Glory</p>
As the previous reviewer suggested, please us a `<hx>` tag here(`h2 to h6`). This is for semantic reasons as this text is considered a subtitle for your webpage. Remember to update all your cards to reflect this change.

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +                <p>see project</p>
Please follow the previous reviewers suggestions here for updating your see project button. Its important for this element to be either an `<a>` tag or a `<button>` tag to improve the semantics of your webpage. Please also follow the advice given for adding styling when the button is hovered or pressed

**Please note: Your project will not be approved until you implement all the required changes**

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +              <h1>About Me</h1>
Please follow the previous reviewers suggestions for updating this element to use another `<hx>` tag

**Please note: Your project will not be approved until you implement all the required changes**

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +            </div>
Please follow the previous reviewers suggestions to make these images background images instead of using an img tag

**Please note: Your project will not be approved until you implement all the required changes**

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +        </div>
Please follow the previous reviewers suggestions to make these images background images instead of using an img tag

**Please note: Your project will not be approved until you implement all the required changes**

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +            <p>Get My Resume</p>
Please follow the previous reviewers suggestions here for updating your get my resume button. Its important for this element to be either an `<a>` tag or a `<button>` tag to improve the semantics of your webpage. Please also follow the advice given for adding styling when the button is hovered or pressed

**Please note: Your project will not be approved until you implement all the required changes**

2023-02-18 08:58 UTC, Shisui6 commented on index.html
> +                  <div class="flex tag-2-container">
As the previous reviewer suggested, kindly update this section to use a `<ul>` tag to wrap all the technology categories, as it is one of the project requirements🙏.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/37116322/219168802-9cd1f71f-48e1-45e6-85b9-38c7991e426d.png">

Also, ensure that each of the technology divs is also wrapped in `<li>` tags. 🫡
- Lastly, please update the list of technologies(HTML, CSS, JS) to be wrapped in a `<ul>` tag insteadof a `<div>`. THe technologies themselves should be `<li>` items

2023-02-18 12:28 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @kalbek, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-18 12:37 UTC, merged